name: Recovery-Builder-Shell

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Shell (Singapore)
        uses: mxschmitt/action-tmate@v3
        env:
          TMATE_OPTS: "-r ap-southeast-1"
          
