name: SSH Terminal (Cloudflared)
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH & Cloudflared
        run: |
          # Password '123' set karein
          echo "runner:123" | sudo chpasswd
          sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo service ssh restart

          # Cloudflared install karein
          curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared.deb

          echo "--- SSH CONNECTION DETAILS ---"
          # Tunnel start karein
          cloudflared tunnel --url ssh://localhost:22
          
